env:
  global:
    - secure: Y+qYl7ybDwWwHHZQ1T8loczK592NDPUBi2CBeWgWpxZDMsRYTggGBuy14ykCmjVb2tgzR2q7QU7oDeBmeqsfcvLmPf4W3kE0j+lm+I8vwP5DrMwYA2UVLuPgqkE21ttaarqzOXQNFuhnHGgkZvGV2Vc6B4vQ/oXBY9VWjd9Ztqs=

before_install:
        - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
        - sudo apt-get -qq update
        - sudo apt-get -qq install libsdl2-dev

language: rust


script:
        - cargo update -v
        - cargo build -v
        - cargo test -v
        - cargo doc --no-deps -v

after_success: 
        - cp -R target/doc doc 
        - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh 
        - rm -r doc 
